openapi: 3.0.0
info:
  title: My Service API
  version: 1.0.0
servers:
  - url: 'http://localhost:8081/api/v1'
paths:
  /microservices:
    get:
      summary: Returns a list of services
      responses:
        '200':
          description: A JSON array of service objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
    put:
      summary: Adds a new service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
      responses:
        '200':
          description: Service created
        '400':
          description: Invalid input
  /microservices/{serviceName}:
    get:
      summary: Returns a specific service
      parameters:
        - name: serviceName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A service object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        '404':
          description: Service not found
components:
  schemas:
    Service:
      type: object
      properties:
        name:
          type: string
        label:
          type: string
        allowedOutputs:
          type: array
          items:
            type: string
